backend/src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from personal.views import home_screen_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('news/', include('news.urls', 'news')),

    # REST FRAMEWORK URLS
    path('api/news/', include('news.api.urls', 'news_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/src/news/api/urls.py
from django.urls import path

from news.api.views import (

	api_detail_news_view,
	ApiNewsListView,

	)

app_name = 'news'

urlpatterns = [
	path('<slug>/', api_detail_news_view, name="detail"),
	path('list', ApiNewsListView.as_view(), name="list"),
]

backend/src/news/urls.py
from django.urls import path
from news.views import detail_news_view

app_name = 'news'

urlpatterns = [
    path('<slug>/', detail_news_view, name="detail"),
 ]

backend/src/news/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver


def upload_location(instance, filename):
	file_path = 'newsPost/{title}-{filename}'.format(title=str(instance.title), filename=filename)
	return file_path


class NewsPost(models.Model):
	title 					= models.CharField(max_length=50, null=True, blank=True)
	body 					= models.TextField(max_length=5000, null=True, blank=True)
	image		 			= models.ImageField(upload_to=upload_location, null=False, blank=False)
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated 			= models.DateTimeField(auto_now=True, verbose_name="date updated")
	slug 					= models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.title

@receiver(post_delete, sender=NewsPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_news_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.title)

pre_save.connect(pre_save_news_post_receiver, sender=NewsPost)

backend/src/personal/models.py
from django.db import models

# Create your models here.

backend/src/news/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView

from news.models import NewsPost
from news.api.serializers import NewsPostSerializer

@api_view(['GET', ])
def api_detail_news_view(request, slug):
	try:
		news_post = NewsPost.objects.get(slug=slug)
	except NewsPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'GET':
		serializer = NewsPostSerializer(news_post)
		return Response(serializer.data)


class ApiNewsListView(ListAPIView):
	queryset = NewsPost.objects.all()
	serializer_class = NewsPostSerializer
	pagination_class = PageNumberPagination

backend/src/news/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from news.models import NewsPost

def detail_news_view(request, slug):
	
	context = {}

	news_post = get_object_or_404(NewsPost, slug=slug)
	context['news_post'] = news_post

	return render(request, 'news/detail_news.html', context)

def get_news_queryset(query=None):
	queryset = []
	queries = query.split(" ")
	for q in queries:
		posts = NewsPost.objects.filter(
			Q(title__contains=q)|
			Q(body__icontains=q)
			).distinct()
		for post in posts:
			queryset.append(post)

	return list(set(queryset))

backend/src/personal/views.py
from django.shortcuts import render
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from news.views import get_news_queryset
from news.models import NewsPost


NEWS_POSTS_PER_PAGE = 10

def home_screen_view(request): 

	context = {}

	query = ""
	query = request.GET.get('q', '')
	context['query'] = str(query)
	print("home_screen_view: " + str(query))

	news_posts = sorted(get_news_queryset(query), key=attrgetter('date_updated'), reverse=True)
	
	# Pagination
	page = request.GET.get('page', 1)
	news_posts_paginator = Paginator(news_posts, NEWS_POSTS_PER_PAGE)

	try:
		news_posts = news_posts_paginator.page(page)
	except PageNotAnInteger:
		news_posts = news_posts_paginator.page(NEWS_POSTS_PER_PAGE)
	except EmptyPage:
		news_posts = news_posts_paginator.page(news_posts_paginator.num_pages)

	context['news_posts'] = news_posts

	return render(request, "personal/home.html", context)

backend/src/news/templates/news/detail_news.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
	.card {
		max-width: 700px;
	}

	.container {
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<img class="card-img-top" src="{{news_post.image.url}}">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">{{news_post.title}}</h2>
				<p class="card-text">{{news_post.body|safe}}</p>
			</div>
			<div class="card-footer text-muted">
				Updated on {{news_post.date_updated}}
			</div>
		</div>
	</div>
</div>

{% endblock content %}

backend/src/news/templates/news/snippets/news_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if news_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ news_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in news_posts.paginator.page_range %}
		{% if news_posts.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if news_posts.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ news_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ news_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

backend/src/news/templates/news/snippets/news_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">

		{% if news_post %}
		<!-- News Post -->
		<div class="card m-auto">
			<a href="{% url 'news:detail' post.slug %}">
				<img class="card-img-top" src="{{news_post.image.url}}">
			</a>
			
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'news:detail' post.slug %}">
					<h2 class="card-title">{{news_post.title}}</h2>
				</a>
				<p class="card-text">{{news_post.body|safe|truncatechars:250}}</p>
			
				
			</div>
			<div class="card-footer text-muted">
			  Updated on {{news_post.date_updated}}
			</div>
		</div>

	</div>
</div>

{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">
					No results
				</h2>
				<p class="card-text">There were no results matching your search: "{{query}}".</p>
			</div>	
		</div>
	</div>
</div>

{% endif %}

backend/src/personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}
	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}
	.news-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}
	.left-column{
		padding:0px;
	}
	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>
<div class="container">
	<div class="row">

		<!-- news feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- News posts-->
			{% if news_posts %}

				{% for post in news_posts %}
				<div class="news-post-container">
					{% include 'news/snippets/news_post_snippet.html' with news_post=post %}
				</div>
			{% endfor %}

			{% else %}
				
				<div class="news-post-container">
					{% include 'news/snippets/news_post_snippet.html' with query=query %}
				</div>

			{% endif %}

			<!-- End News posts-->

		<!-- Pagination -->
		{% include 'news/snippets/news_post_pagination.html' with news_posts=news_posts %}

		</div>
		<!-- end news feed -->

	</div>
</div>

{% endblock content %}

backend/src/templates/base.html
<!DOCTYPE html>
<html>

<head>

	<title>NewsApp</title>

	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	{% include 'snippets/header.html' %}
	{% include 'snippets/base_css.html' %}

</head>

<body>

	<style type="text/css">
		.main{
			min-height: 100vh;
			height: 100%;
		}
	</style>

	<div class="main">
		{% block content %}
	
		{% endblock content %}
	</div>

	{% include 'snippets/footer.html' %}

</body>

</html>

backend/src/templates/snippets/base_css.html
<style type="text/css">
	body{
		background-color: #f2f2f2
	}
</style>

backend/src/templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<div class="d-flex flex-row align-items-center footer bg-white border-top shadow-lg">
	<p class="m-auto">News App | 2020</p>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

backend/src/templates/snippets/header.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style type="text/css">
	@media (min-width: 768px) {
  html {
    	font-size: 16px;
  		}
	}

	.container {
	  max-width: 960px;
	}

	.pricing-header {
	  max-width: 700px;
	}

	.card-deck .card {
	  min-width: 220px;
	}

	.search-bar{
		max-width: 500px;
		width: 100%;
	}

	form{
		width: 100%;
	}
</style>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

	<div class="search-bar mt-sm-2 mr-2">
		<form onsubmit="return executeQuery();">
			<input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
		</form>
	</div>

</div>

<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script>

<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script>
<script>
function executeQuery() {
    var query = document.getElementById('id_q').value;
    window.location.replace("http://127.0.0.1:8000/?q=" + query)=
    return false
}
</script>